name: llm
channels:
  - pytorch
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - cpuonly
  - python=3.11
  - numpy=1.26.4
  - ipython
  - pip
  - pip:
    - pytest
    - datasets==2.15.0
    - transformers
    - accelerate
    - peft
